services:
  api:
    image: finsmart
    ports:
      - "8080:8080"
    #environment:
      #SPRING_PROFILES_ACTIVE: prod
    networks:
      - app-network
    depends_on:
      - db

  db:
    image: postgres
    container_name: postgres-db
    restart: always
    environment:
      POSTGRES_DB: finsmartdb
      POSTGRES_USER: finsmart
      POSTGRES_PASSWORD: 123456
    ports:
      - "5432:5432"
    networks:
      - app-network # Para poder se conectar com o pgadmin

  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "8000:80"
    depends_on:
      - db
    networks:
      - app-network # Para poder se conectar com o postgres como nome db

networks: # Declaração para criação da rede
  app-network:
    driver: bridge