services:
  api:
    image: finsmart
    ports:
      - "8080:8080"
    environment:
      SPRING_PROFILES_ACTIVE: prod
    networks:
      - app-network
    depends_on:
      - db

  db:
    image: postgres:18.1
    container_name: postgres-db
    restart: always
    environment:
      POSTGRES_DB: finsmartdb
      POSTGRES_USER: finsmart
      POSTGRES_PASSWORD: 123456
    ports:
      - "5432:5432"
    networks:
      - app-network # Para poder se conectar com o pgadmin

networks: # Declaração para criação da rede
  app-network:
    driver: bridge